AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'test/**/*'
    - 'db/schema.rb'
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
